### ISSUE TITLE
Calls realpath("-", …)

### ISSUE THREAD

**Issue by jwilk** [gwsw/less#289]
I spotted this in `strace` output for `less` (which was called without the filename argument):
```
readlink("/home/jwilk/-", 0x7ffe8d27f0c0, 1023) = -1 ENOENT (No such file or directory)
readlink("/home/jwilk/-", 0x7ffe8d27f0c0, 1023) = -1 ENOENT (No such file or directory)
```

I've managed to get this backtrace:
```
#3  0x000055713d3db30d in realpath (__resolved=0x7ffca7650900 "\340\017e\247\374\177", __name=0x55713d3f0785 "-") at /usr/include/x86_64-linux-gnu/bits/stdlib.h:48
#4  lrealpath (path=path@entry=0x55713d3f0785 "-") at filename.c:805
#5  0x000055713d3dc68e in find_ifile (filename=0x55713d3f0785 "-") at ifile.c:225
#6  get_ifile (filename=filename@entry=0x55713d3f0785 "-", prev=0x0) at ifile.c:261
#7  0x000055713d3da5ea in edit (filename=0x55713d3f0785 "-") at edit.c:232
#8  edit_stdin () at edit.c:757
#9  edit_first () at edit.c:570
#10 0x000055713d3cecd0 in main (argc=<optimized out>, argv=0x7ffca7651aa8) at main.c:276
```
So apparently `less` calls `realpath("-", …)`. This is weird.

Tested with git master (ae57646896bd218b1c5c3087d8937da635fb9ef7).

**Comment by gwsw** [comment]
Fixed in ccb6da07c1e99ae3ad1218eaa8fecf514e9f45e6.
